server:
  port: 8095

spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/max
  username: oscarlo
  password: oscarVenturenixLab2023.
spring.jpa:
  show-sql: true
  hibernate.ddl-auto:
    create-drop 
spring.sql.init:
  mode: always # always
  platform: mysql
spring.profiles.active: enableScheduling